WIP: #91 Changed stuff to bootstrap uploader and has desired behaviour now
DanGravel/SYSC4806 pull request #123
Opened 2019-03-18 22:25 UTC by br0wncrust4cean

2019-03-18 23:44 UTC, Taz-Z commented
If you choose a file and dont hit upload, then choose another file but this time you hit escape, it says you dont have a file picked and you cant upload. However, the previous file name is still populated.

So either

a) Clear the file name 

or preferred 

b) Remember which file was chosen last, and then upload this one when upload is hit

2019-03-18 23:44 UTC, Taz-Z requested changes

2019-03-18 23:44 UTC, Taz-Z commented on Project/src/main/resources/static/css/upload.css
>      display: none;
Check PR, has comment

2019-03-19 04:18 UTC, acournoyer1 approved these changes

2019-03-19 16:17 UTC, Taz-Z approved these changes

2019-03-19 16:17 UTC, merged