#147 Added custom exception to return error response
DanGravel/SYSC4806 pull request #148
Opened 2019-03-25 01:35 UTC by DanGravel

2019-03-25 01:38 UTC, br0wncrust4cean requested changes

2019-03-25 01:38 UTC, br0wncrust4cean commented on Project/src/main/java/app/RegisterController.java
> +    @ResponseStatus(value= HttpStatus.INTERNAL_SERVER_ERROR, reason="User already exists")
Can you move this to a class in the Exceptions folder?

2019-03-26 14:15 UTC, br0wncrust4cean approved these changes

2019-03-26 19:04 UTC, liamhickey approved these changes

2019-03-26 19:04 UTC, merged