#149 Moved login and base url controller logic to their own classes
DanGravel/SYSC4806 pull request #150
Opened 2019-03-25 01:51 UTC by DanGravel

2019-03-26 14:19 UTC, br0wncrust4cean requested changes
Small change

2019-03-26 14:19 UTC, br0wncrust4cean commented on Project/src/main/java/app/LoginController.java
> +public class LoginController {
Just for design sake can you make this extend app.Controller please?

2019-03-26 18:04 UTC, br0wncrust4cean approved these changes

2019-03-27 04:22 UTC, Taz-Z approved these changes

2019-03-27 04:22 UTC, merged